import { profile, dossier } from "@/data/profile";
import { projects } from "@/data/projects";
import { Label, Panel, SpecSheet } from "@/components/ui/primitives";

/**
 * Asymmetric two columns: the argument on the left, the instrument panel on
 * the right. The verification index sits under the prose so the left column
 * runs to the same depth as the right rather than stopping short of it.
 */
export function About() {
  // The claims the prose makes, each with the repository that settles it.
  const checkable = [...projects].sort((a, b) => b.range - a.range).slice(0, 3);

  return (
    <div className="grid gap-12 lg:grid-cols-[1.15fr_1fr] lg:gap-16">
      <div className="flex flex-col">
        <div className="mb-5">
          <Label>How I work</Label>
        </div>

        {profile.about.map((p) => (
          <p
            key={p.slice(0, 24)}
            className="mb-5 font-mono text-sm leading-[1.85] text-muted-foreground"
          >
            {p}
          </p>
        ))}

        <Panel label="Start checking here" className="mt-5">
          <ul className="divide-y divide-border">
            {checkable.map((p) => (
              <li key={p.slug} className="py-3">
                <div className="flex items-baseline justify-between gap-4">
                  <a
                    href={p.repoUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="font-mono text-sm underline underline-offset-4"
                    style={{ color: "var(--signal)" }}
                  >
                    {p.name}
                  </a>
                  <span className="shrink-0 font-mono text-[11px] tabular-nums text-muted-foreground">
                    {p.metrics[0].label} {p.metrics[0].value}
                  </span>
                </div>
                <p className="mt-1 font-serif text-sm text-muted-foreground">
                  {p.summary}
                </p>
              </li>
            ))}
          </ul>
          <p className="mt-4 font-mono text-[10px] leading-relaxed tracking-[0.12em] text-muted-foreground/60 uppercase">
            Each figure above is generated by a script in the repository it
            links to
          </p>
        </Panel>
      </div>

      <aside className="space-y-10">
        <div>
          <div className="mb-4">
            <Label>The dossier</Label>
          </div>
          <SpecSheet
            rows={dossier.map((d) => ({ label: d.label, value: d.value }))}
          />
        </div>

        <div>
          <div className="mb-4">
            <Label>Education</Label>
          </div>
          <ul className="divide-y divide-border border-y border-border">
            {profile.education.map((e) => (
              <li key={e.degree} className="py-3">
                <p className="text-sm">{e.degree}</p>
                <p className="mt-1 font-mono text-[10px] tracking-[0.15em] text-muted-foreground uppercase">
                  {e.institution} · {e.period}
                </p>
              </li>
            ))}
          </ul>
        </div>
      </aside>
    </div>
  );
}
