import { profile, dossier } from "@/data/profile";
import { projects } from "@/data/projects";
import {
  Chip,
  Label,
  Panel,
  PixelRule,
  SpecSheet,
  Stamp,
} from "@/components/ui/primitives";

export function About() {
  // The claims the prose makes, each with the repository that settles it.
  const checkable = [...projects].sort((a, b) => b.range - a.range).slice(0, 3);

  return (
    <div className="space-y-14">
      {/*
       * Statement band. A slab of dithered ground with the thesis set large —
       * the section opens by asserting rather than easing in.
       */}
      <div className="dither relative border-y-2 border-border py-10">
        <div className="corner-ticks relative px-4 md:px-8">
          <p className="max-w-5xl font-serif text-3xl leading-[1.15] text-foreground md:text-5xl">
            {profile.statement}
          </p>
        </div>
      </div>

      <div className="grid gap-12 lg:grid-cols-[1.15fr_1fr] lg:gap-16">
        {/* min-w-0: a grid item defaults to min-width:auto, so it refuses to
            shrink below its content's minimum and pushes past the track. That
            is what put this column at 304px inside a 272px track on a 320px
            screen, taking the whole document 8px wide. */}
        <div className="flex min-w-0 flex-col">
          <div className="mb-4 flex items-center gap-3">
            <Stamp>How I work</Stamp>
            <div className="flex-1">
              <PixelRule />
            </div>
          </div>

          {profile.about.map((p) => (
            <p
              key={p.slice(0, 24)}
              className="mb-5 font-mono text-sm leading-[1.85] text-muted-foreground"
            >
              {p}
            </p>
          ))}

          <Panel label="Start checking here" className="mt-5" signal ticks>
            <ul className="divide-y-2 divide-border">
              {checkable.map((p, i) => (
                <li key={p.slug} className="py-3">
                  {/* Wraps rather than holding one line. The metric is
                      shrink-0 by design — "MAE 255 MW" must not break across
                      lines — so on a 320px screen it was the last seven pixels
                      that took the whole document wider than the viewport. */}
                  <div className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
                    <span className="flex min-w-0 items-baseline gap-3">
                      <span className="font-mono text-[10px] text-muted-foreground/50">
                        {String(i + 1).padStart(2, "0")}
                      </span>
                      <a
                        href={p.repoUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="font-mono text-sm underline underline-offset-4"
                        style={{ color: "var(--signal)" }}
                      >
                        {p.name}
                      </a>
                    </span>
                    <span className="shrink-0 font-mono text-[11px] tabular-nums text-muted-foreground">
                      {p.metrics[0].label} {p.metrics[0].value}
                    </span>
                  </div>
                  <p className="mt-1 pl-7 font-serif text-sm text-muted-foreground">
                    {p.summary}
                  </p>
                </li>
              ))}
            </ul>
            <p className="mt-4 font-mono text-[10px] leading-relaxed tracking-[0.12em] text-muted-foreground/60 uppercase">
              Each figure above is generated by a script in the repository it
              links to
            </p>
          </Panel>
        </div>

        {/* min-w-0 for the same reason as the column above: below the lg
            breakpoint both sit in one shared track, so whichever refuses to
            shrink sizes the track for both. */}
        <aside className="min-w-0 space-y-10">
          <div>
            <div className="mb-4 flex items-center gap-3">
              <Stamp>The dossier</Stamp>
              <div className="flex-1">
                <PixelRule />
              </div>
            </div>
            <SpecSheet
              rows={dossier.map((d) => ({ label: d.label, value: d.value }))}
            />
          </div>

          <div>
            <div className="mb-4 flex items-center gap-3">
              <Stamp>Education</Stamp>
              <div className="flex-1">
                <PixelRule />
              </div>
            </div>
            <ul className="divide-y-2 divide-border border-y-2 border-border">
              {profile.education.map((e) => (
                <li key={e.degree} className="py-3">
                  <p className="text-sm">{e.degree}</p>
                  <p className="mt-1 font-mono text-[10px] tracking-[0.15em] text-muted-foreground uppercase">
                    {e.institution} · {e.period}
                  </p>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <div className="mb-4">
              <Label>Off screen</Label>
            </div>
            <div className="flex flex-wrap gap-1.5">
              {profile.interests.map((i) => (
                <Chip key={i}>{i}</Chip>
              ))}
            </div>
          </div>
        </aside>
      </div>
    </div>
  );
}
